
language: android
jdk: oraclejdk8
env:
  matrix:
  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=23.0.2 ANDROID_TARGET=android-23
    ANDROID_ABI=armeabi-v7a

before_install:
 - chmod +x gradlew

android:
  components:
    - useLibrary 'org.apache.http.legacy'
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - "$ANDROID_TARGET"
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-$ANDROID_TARGET

before_script:
  - cd android
script:
  - ./gradlew build
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

notifications:
  webhooks:
    urls:
    #- https://webhooks.gitter.im/e/6967b4aa34219a8450e6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
